server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo2
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: DEMO2

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
