server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo1
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  application:
    name: DEMO1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/