server:
  port: 8083

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: demo2
          uri: lb://demo2
          predicates:
            - Path=/demo2/**
          filters:
            - AuthenticationFilter

        - id: demo1
          uri: lb://demo1
          predicates:
            - Path=/demo1/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
